apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: j8xuhc7lm-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/j8xuhc7lm-dotnet-basic